### ISSUE TITLE
PaperMC 1.19.2で動かない

### ISSUE THREAD

**Issue by mk499490** [SimplyRin/InventorySaver#1]
# スタックトレース

```
[15:55:04] [Server thread/INFO]: [InventorySaver] Enabling InventorySaver v2.0
[15:55:04] [Server thread/INFO]: [InventorySaver] Zipping previous day's data into a ZIP file...
[15:55:04] [Server thread/ERROR]: Error occurred while enabling InventorySaver v2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot read the array length because "<local4>" is null
	at net.simplyrin.inventorysaver.InventorySaver.saveToZip(InventorySaver.java:117) ~[InventorySaver-2.0.jar:?]
	at net.simplyrin.inventorysaver.InventorySaver.onEnable(InventorySaver.java:91) ~[InventorySaver-2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-124]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-124]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-124]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-124]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-124]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1125) ~[paper-1.19.2.jar:git-Paper-124]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-124]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:55:04] [Server thread/INFO]: [InventorySaver] Disabling InventorySaver v2.0
```

# 環境

- **OS**: Windows11 Pro 64bit
- **Java**: java version "17.0.3" 2022-04-19 LTS
- **PaperMC**: 1.19.2 #124

**Comment by SimplyRin** [comment]
[v2.1](https://github.com/SimplyRin/InventorySaver/releases/tag/2.1) で修正しました。
